name: Functions CI/CD

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'functions/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'functions/**'
  workflow_dispatch:

env:
  GCP_REGION: 'us-central1'
  FUNCTION_NAME: 'alert-handler'

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install pip-audit
        run: pip install pip-audit
      
      - name: Scan dependencies
        working-directory: ./functions/alert-handler
        run: |
          pip-audit -r requirements.txt --desc || true
        continue-on-error: true
      
      - name: Run Bandit
        run: |
          pip install bandit[toml]
          bandit -r functions/ -ll || true
        continue-on-error: true

  deploy:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --gen2 \
            --runtime=python310 \
            --region=${{ env.GCP_REGION }} \
            --source=./functions/alert-handler \
            --entry-point=handle_alert \
            --trigger-topic=sre-alerts \
            --service-account=alert-handler-sa@uber-clone-api-325213.iam.gserviceaccount.com \
            --set-env-vars="VERSION=${{ github.sha }}"
